# Generated by Django 4.1.3 on 2023-02-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=320)),
                ('comment', models.TextField()),
                ('user_query_number', models.CharField(default='', max_length=254)),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'User Queries',
            },
        ),
        migrations.CreateModel(
            name='QueryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_query_response', to='contact.userquery')),
            ],
        ),
    ]
